#!/bin/sh

https_var="https_crt_file"
https_file="cert.tgz"
https_jffs="/jffs/ssl"
https_jffs_old="/jffs/https"
https_certs="/etc/cert.pem /etc/key.pem"
lighttpd_certkey="/etc/server.pem"
OLDIF=IFS; IFS=" ";

mkdir -p "$https_jffs"
err=0

VARNAME=$https_var
    FILEPATH="${https_jffs}/${https_file}"
    tar -C / -czf $FILEPATH ${https_certs} > /dev/null 2>&1
    for fn in ${https_certs}
    do
		cp -af $fn ${https_jffs}
    done
	cp -af ${lighttpd_certkey} ${https_jffs}
    printf "%-25s" "Processing $VARNAME"
    if [ -f $FILEPATH ]; then
		echo -e "\tDone"
    else
		echo -e "\tCould not create saved cert"
	err=1
    fi
    if [ -d "${https_jffs_old}" ]; then
		rm -rf ${https_jffs_old}
	fi
	ln -sf ${https_jffs} ${https_jffs_old}

IFS=OLDIFS;
if [ $err -eq 0 ]; then
	nvram set $VARNAME=${FILEPATH}
	nvram commit
	echo "Please reboot via web gui"
else
	echo "Errors found!"
fi
