#!/bin/sh

sshd_vars="sshd_authkeys sshd_hostkey sshd_dsskey sshd_ecdsakey"
sshd_files="sshd_authkeys dropbear_rsa_host_key dropbear_dss_host_key dropbear_ecdsa_host_key"
sshd_dir="/jffs/dropbear/"
OLDIF=IFS; IFS=" ";

err=0
let count=1
for VARNAME in $sshd_vars;
do
    FILENAME=$(echo $sshd_files | cut -d " " -f$count)
    FILEPATH=${sshd_dir}$FILENAME
    printf "%-48s" "Processing $FILEPATH"
    if [ $count -eq 1 ]; then
        VALUE=$(head -c 2999 $FILEPATH)
    else
        VALUE=$(head -c 2999 $FILEPATH | openssl enc -base64 | tr -d '\n')
    fi
    lVALUE=$(echo ${#VALUE})
    if [ $lVALUE -gt 0 ]; then
	nvram set $VARNAME="${VALUE}"
	echo -e "\tDone"
    else
	echo -e "\tEmpty"
	err=1
    fi
    let count=count+1
done

IFS=OLDIFS;
if [ $err -eq 0 ]; then
	nvram commit
	echo "Please reboot via web gui"
else
	echo "Errors found!"
fi
exit 0
